#!/bin/sh
USER_DIR="$(pwd)"
SCRIPT_DIR="$(cd "$(dirname "${0}")" && pwd)"
TARGET_SCRIPT="$(readlink "${0}")"
if [ -n "${TARGET_SCRIPT}" ] ; then
  exec "${SCRIPT_DIR}"/"${TARGET_SCRIPT}" "$@" || exit 1
else
  cd "${SCRIPT_DIR}" || exit 1
fi

exec 3>&1
cd "${USER_DIR}" && yarn --cwd "${SCRIPT_DIR}" -s run hokey "$@" 2>&1 >&3 3>&- | grep -v 'No license field' 3>&-
exec 3>&-
