#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${0}")" && pwd)"
BASE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

LANGS="${1:-"all"}"
if [[ "${LANGS}" == "all" ]] ; then
  LANGS="$(cat "${BASE_DIR}/scripts/all-langs-except-en.txt")"
fi
MODE=${2:-"all"}

FORCE="${HOKEY_FORCE}"
if [[ -n "${HOKEY_FORCE}" && "${HOKEY_FORCE}" == "force" ]] ; then
  FORCE="--force"
else
  FORCE=""
fi

cd "${BASE_DIR}"
if [[ "${MODE}" == "all" || "${MODE}" == "locales" ]] ; then
  echo " ========== Processing messages/locales_LANG.js ... "
  ./hokey \
      --input-language en \
      --languages "${LANGS}" \
      --outfile messages/locales_LANG.js \
      --handlebars "${FORCE}" \
      ./messages/locales_en.js
fi

if [[ "${MODE}" == "all" || "${MODE}" == "messages" ]] ; then
  echo " ========== Processing messages/LANG_messages.js ... "
  ./hokey \
      --input-language en \
      --languages "${LANGS}" \
      --outfile messages/LANG_messages.js \
      --handlebars "${FORCE}" \
      ./messages/en_messages.js
fi

if [[ "${MODE}" == "all" || "${MODE}" == "readme" ]] ; then
  echo " ========== Processing README.md ... "
  ./hokey \
      --input-language en \
      --languages "${LANGS}" \
      --outfile lang/LANG \
      --excludes lang/ node_modules/ \.git/ tmp/ \
      --filter "${BASE_DIR}/util/filterReadme.js" \
      --markdown "${FORCE}" \
      --match README\.md \
      .
fi
echo " ========== DONE! "
