#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${0}")" && pwd)"
BASE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

LANGS="${1:-$(cat "${BASE_DIR}/scripts/all-langs-except-en.txt")}"

FORCE="${HOKEY_FORCE}"
if [[ -n "${HOKEY_FORCE}" && "${HOKEY_FORCE}" == "force" ]] ; then
  FORCE="--force"
else
  FORCE=""
fi

cd "${BASE_DIR}" && \
echo " ========== Processing messages/locales_LANG.js ... " && \
./hokey \
    --input-language en \
    --languages "${LANGS}" \
    --outfile messages/locales_LANG.js \
    --handlebars "${FORCE}" \
    ./messages/locales_en.js && \
echo " ========== Processing messages/LANG_messages.js ... " && \
./hokey \
    --input-language en \
    --languages "${LANGS}" \
    --outfile messages/LANG_messages.js \
    --handlebars "${FORCE}" \
    ./messages/en_messages.js && \
echo " ========== Processing README.md ... " && \
./hokey \
    --input-language en \
    --languages "${LANGS}" \
    --outfile lang/LANG \
    --excludes lang/ node_modules/ \.git/ tmp/ \
    --filter "${BASE_DIR}/util/filterReadme.js" \
    --markdown "${FORCE}" \
    --match README\.md \
    . && \
echo " ========== DONE! "
